### PR TITLE
fix deprecated functions

### LINKED ISSUE #19: Upgrade deprecated functions for Googlesheets and Googledrive packages
`Googlesheets`and `Googledrive` packages have been updated to use the input argument `client` instead of `app`. This causes login issues when packages are updated.

```
library('chchpd')
```

> Data import functions for the Christchurch Longitudinal Parkinson's Study. Should be run only by accredited researchers at NZBRI, who have authorised access to the data sources.
> Warning messages:
> 1: The `app` argument of `gs4_auth_configure()` is deprecated as of googlesheets4
> 1.1.0.
> ℹ Please use the `client` argument instead.
> ℹ The deprecated feature was likely used in the chchpd package.
>   Please report the issue to the authors.
> This warning is displayed once every 8 hours.
> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
> generated. 
> 2: The `app` argument of `drive_auth_configure()` is deprecated as of googledrive
> 2.1.0.
> ℹ Please use the `client` argument instead.
> ℹ The deprecated feature was likely used in the chchpd package.
>   Please report the issue to the authors.

### PR DESCRIPTION
**Pull request by rezashr**
Update `googlesheets` and `googledrive` packages and update their associated deprecated functions. Fixes #19

### CODE REVIEW

**Comment by zenourn** [comment]
Thanks heaps Reza, looks great! @m-macaskill - would it be possible to document the release procedure so I can take over that role?

**Comment by rezashr** [comment]
@m-macaskill to confirm, I think the only remaining step is to merge and create a tag (version updated and roxigenised already). I'll try to automate this process soon.

**Comment by m-macaskill** [comment]
Hi - Reza thanks again for updating this moving target…

Daniel - yes, the key thing is to tag each release with the version number. To keep potentially multi-line notes for the tag, I store them in a text file until ready to use:
`git tag -a v0.5.3 --file="tag_message.txt"` 
We (are supposed to) use semantic versioning. So we are well overdue to increment to a 1.0.0 release!
NB we should probably also update the "releases" to match the tags. I think releases are a Github rather than git thing and not entirely sure of the relationship, which I guess can be arbitrary. But they are more visible to the casual user (whereas tags require to be clicked through to view on the Github page).

From my notes:
- manually update version number in the DESCRIPTION file
- run `devtools::document()` which under the hood calls roxygen I think. Might not change anything if no function help strings have changed but you never know. It is a bit idiosyncratic when the `?chchpd` help will show the new version number.
- If changed, don't forget to knit the README.Rmd file to produce the coresponding .md file for the Github page. This doesn't happen automatically when generating the other documentation.

**Comment by m-macaskill** [comment]
If tidying up for a handover, would probably also be a good idea to rename `master` to be `main`, in accordance with modern practice.

Or even better, decide on a [more disciplined collaborative flow pattern](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), like having persistent `main`, `dev`, and `release` branches, with temporary feature branches. But probably not such an issue for a relatively mature package that won't ever have more than a couple of developers contributing. There may be some quite substantial development to come as the data sources evolve, but I'm guessing that will largely fall to Daniel to adapt to…

**Comment by rezashr** [comment]
Having multiple active branches don't really make sense here. Even large projects such as `powershell`, `pytorch`, and `tensorflow` just use feature-/task-branch approach which gets merged into `default`. Although we could create `dev` and `release` branches, I don't see how we could benefit from it here. [This](https://medium.com/better-software/micro-services-git-d840305e6220) is a good read about git for microservices. On the other hand, `dev`/`release` git flow seems like a good choice for a monolithic application.

**Comment by rezashr** [comment]
For now, I'll merge this and manually tag the version.

**Pull request merged**
